### ISSUE TITLE
Pipenv assumes Pipfile is in $cwd and creates one if it is not

### ISSUE THREAD

**Issue by mrzarquon** [snyk/snyk-python-plugin#133]
- `node -v`: v15.7.0
- `npm -v`: 7.4.3
- `snyk -v`: 1.457.0
- Command run:

### Expected behaviour

Running `snyk test --file=folder/to/Pipfile` should behave the same as if I were running `snyk test` in the same folder as the Pipfile.

### Actual behaviour

Instead it errors out with missing packages (due to not loading the virtual environment) and also generates a phantom Pipfile in the directory I executed snyk test from.

### Steps to reproduce
```
❯ mkdir -p foo/bar/baz
❯ cd foo/bar/baz
❯ pipenv --python 3.9
❯ pipenv install pysnyk
❯ cd ../../..
❯ snyk test --file=foo/bar/baz/Pipfile
Creating a Pipfile for this project...
Required packages missing: pysnyk

Please run `pipenv update`. If the issue persists try again with --skip-unresolved.
```

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by aviadhahami** [comment]
Was merged on https://github.com/snyk/snyk-python-plugin/pull/134 :D 
Closing the issue :)
