### ISSUE TITLE
Support pip's editable package subdirectory component

### ISSUE THREAD

**Issue by chris-griffin** [snyk/snyk-python-plugin#14]
Issue https://github.com/snyk/snyk/issues/109 is caused by https://github.com/snyk/snyk-python-plugin/blob/master/plug/requirements/requirement.py#L26 not supporting the [subdirectory component](https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support)

**Comment by darscan** [comment]
Thanks for hunting that down! I'll take a look

**Comment by darscan** [comment]
Ah, just saw your PR! Thanks!

**Comment by darscan** [comment]
Fixed by https://github.com/snyk/snyk-python-plugin/pull/20
