### ISSUE TITLE
pipfile support in github

### ISSUE THREAD

**Issue by jdogmcsteezy** [snyk/snyk-python-plugin#195]
Is `Pipfile.lock` (or even `Pipfile`) supported though GitHub? It doesn't show up when I imported the project and doesn't appear to be documented ([docs](https://docs.snyk.io/products/snyk-open-source/language-and-package-manager-support/snyk-for-python) still just say "CLI" and "Licensing" for `pipenv`.

_Originally posted by @jeremywadsack in https://github.com/snyk/snyk-python-plugin/issues/23#issuecomment-1297796982_

I too would like this, and I am sure many others.  CLI support is great but when teams and orgs are constantly changing it is really convenient to not have to set up pre-commit hooks for everyone

**Comment by avijitpal9** [comment]
Is the pipfile (pipfile.lock) support though github on the product roadmap ? Any plans on rolling out this feature ?
