### ISSUE TITLE
`snyk test` failing with `Required packages missing: enum34` with latest Snyk version 1.1153.0

### ISSUE THREAD

**Issue by mishless** [snyk/snyk-python-plugin#208]
- `node -v`:`v18.11.0`
- `npm -v`:`9.2.0`
- `snyk -v`:`1.1153.0`
- `python -v`: `Python 3.10.6`
- OS: Mac and Linux
- Command run:`snyk test --file=requirements.txt --command=python --package-manager=pip --severity-threshold=high`

### Expected behaviour
Result from testing the dependencies for vulnerabilities.

### Actual behaviour
The following error is observed:
```
Required packages missing: enum34
Please run `pip install -r requirements.txt`. If the issue persists try again with --skip-unresolved.
```

### Steps to reproduce
The `requirements.txt` file contains a single line:
`google_api_python_client==2.86.0`

`pip install -r requirements.txt`
`snyk test --file=requirements.txt --command=python --package-manager=pip --severity-threshold=high`

When I use `snyk v1.1152.0` everything works as expected.

**Comment by jmahlik** [comment]
Seeing the same thing with the standard library module `typing` on python 3.10.  It might be related to dependency parsing? This shouldn't be picking up standard library modules to my knowledge.

And also with a dependency that isn't even in the requirements file nor in the venv: `asynctest`

The closest thing to typing in the first requirements file is `typing_extentions`.

```bash
python -m pip freeze --exclude-editable > requirements.txt
snyk test --file=requirements.txt --org=$ORG --json-file-output=snyk.json
Required packages missing: typing
Please run `pip install -r requirements.txt`. If the issue persists try again with --skip-unresolved.
```

The closest thing to `asynctest` in this one is `async-timeout`.

```bash
# Install deps, we can see asynctest is not in the requirements, they are in alphabetical order
python -m pip install .
...
Successfully installed IPython-8.13.2 aiohttp-3.8.4 aiohttp-cors-0.7.0 aiosignal-1.3.1 asttokens-2.2.1 async-timeout-4.0.2 attrs-23.1.0 backcall-0.2.0 blessed-1.20.0 boto3-1.26.129 botocore-1.29.129 ... 

python -m pip freeze --exclude-editable  > requirements.txt
snyk test --file=requirements.txt --org=$ORG --json-file-output=snyk.json 
Required packages missing: asynctest
Please run `pip install -r requirements.txt`. If the issue persists try again with --skip-unresolved.
```

**Comment by candrews** [comment]
[Snyk CLI 1.1153.0](https://github.com/snyk/cli/releases/tag/v1.1153.0) upgraded `snyk-python-plugin` from `1.24.4` to `1.25.1`: https://github.com/snyk/cli/compare/v1.1152.0...v1.1153.0#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519L79

Therefore, these are the relevant changes: https://github.com/snyk/snyk-python-plugin/compare/v1.24.4...v1.25.1

**Comment by candrews** [comment]
Has someone created a Snyk support request at https://support.snyk.io/hc/en-us/requests/new yet?

I suspect this issue impacts all users of snyk cli who scan python projects.

**Comment by QuicksilverMachine** [comment]
It seems to be failing the "less than" python version checks, since `asynctest` library is required by `aiohttp` for python versions older than 3.7. So it's requesting _all_ compatibility libraries.
