### ISSUE TITLE
Python 3.12 support: distutils and setuptools

### ISSUE THREAD

**Issue by jmahlik** [snyk/snyk-python-plugin#226]
- `node -v`: v18.17.1
- `npm -v`: 8.18.0
- `snyk -v`: 1.1227.0

- Command run:
`snyk test --file=requirements.txt --org=$SNYK_ORG --severity-threshold=medium --debug`

### Expected behaviour
Snyk test to function. In python 3.12 distutils will be removed and it is no longer safe to assume setuptools will be automatically added to all virtual environments. The current cli assumes these modules will be available. 

https://github.com/snyk/snyk-python-plugin/blob/556b0295fca407ad54859baf0b688beb288687f4/pysrc/setup_file.py

This may be a good time to move away from [pkg_resources](https://setuptools.pypa.io/en/latest/pkg_resources.html) to get the [working set](https://github.com/snyk/snyk-python-plugin/blob/556b0295fca407ad54859baf0b688beb288687f4/pysrc/README.md?plain=1#L12) as well. It has been deprecated for a long time and has some nasty side effects on import. It may stop functioning one day. I realize it's vendored, but might be good to get away from it if possible.

Resources:
* https://docs.python.org/3.12/whatsnew/3.12.html
* https://peps.python.org/pep-0632/
* https://peps.python.org/pep-0632/#migration-advice
* https://docs.python.org/3.12/whatsnew/3.12.html#ensurepip

### Actual behaviour
Snyk test errors trying to import setuptools.

```
  snyk:run-test Error running test {
  error: 'Traceback (most recent call last):\r\n' +
    '  File "C:\\Users\\...\\AppData\\Local\\Temp\\tmp-4864-4ryp6LdWeubv\\pip_resolve.py", line 10, in <module>\r\n' +
    '    import setup_file\r\n' +
    '  File "C:\\Users\\...\\AppData\\Local\\Temp\\tmp-4864-4ryp6LdWeubv\\setup_file.py", line 3, in <module>\r\n' +
    '    import setuptools\r\n' +
    "ModuleNotFoundError: No module named 'setuptools'\r\n"
}
```

### Steps to reproduce
One can recreate the behavior on python3.11 with virtualenv.

```bash
python -m pip install virtualenv 
# This will be the default in 3.12 
virtualenv venv --no-setuptools
. venv/bin/activate 
snyk test --file=requirements.txt --org=$SNYK_ORG --severity-threshold=medium --debug
```

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by jmahlik** [comment]
This is still an issue.

**Comment by gemaxim** [comment]
Hello 👋 is this still an issue with the latest cli version? I was not able to reproduce on my end (uninstalled setuptools before doing the steps, double checked that it's not installed before doing 'snyk test')

**Comment by jmahlik** [comment]
> Hello 👋 is this still an issue with the latest cli version? I was not able to reproduce on my end (uninstalled setuptools before doing the steps, double checked that it's not installed before doing 'snyk test')

I can confirm it works without setuptools on python 3.12.

```bash
snyk --version
1.1291.1

python3.12 --version
Python 3.12.4

python3.12 -m venv test-snyk
. ./test-snyk/Scripts/activate
python --version
Python 3.12.4

python -m pip list
Package Version
------- -------
pip     24.0

# Needed something to install
python -m pip install 'typing-extensions==4.12.2'

python -m pip list
Package           Version
----------------- -------
pip               24.0
typing_extensions 4.12.2

python -m pip freeze > requirements.txt

cat requirements.txt
typing_extensions==4.12.2

snyk test --file=requirements.txt

✔ Tested 1 dependencies for known issues, no vulnerable paths found.
```

**Comment by RollerKnobster** [comment]
How was this achieved? I am currently experiencing a problem where snyk downgrades `setuptools` already installed in an environment to `68.0.0` upon running `snyk test`. Does it now install `setuptools` implicitly before running the test?
