### ISSUE TITLE
Pipfile support

### ISSUE THREAD

**Issue by sobolevn** [snyk/snyk-python-plugin#23]
Right now there are multiple ways to specify dependencies in `python`:
1. `requirements.txt`
2. `setup.py`
3. `Pipfile`

It would be really great to see `Pipfile` support! Any plans on it?

**Comment by jsf9k** [comment]
I'd also enjoy some `setup.py` support.  Right now snyk can't seem to test some of my projects because all the dependencies are in `setup.py` and the `requirements.txt` file just looks like `-e .[dev]`.

**Comment by darscan** [comment]
Hello! We have plans to support Pipenv and `setup.py` files, but I can't comment on any particular timeframe at this point. Thanks for nudging though, it helps with the roadmap :)

**Comment by adamcharnock** [comment]
Yep, this one is pretty crucial for me. My open source projects all specify deps using `setup.py`, and my client work all uses `Pipfiles`s.

**Comment by adrukh** [comment]
We have released `Pipfile` support with https://github.com/snyk/snyk/releases/tag/v1.90.0

Please let us know what you think!

**Comment by tommilligan** [comment]
Really like that `Pipfile` support is taking off. The crucial thing missing for me is the ability to treat `Pipfile.lock` in the same way as `yarn.lock` - scanning it shouldn't require the packages to actually be installed first, or `pipenv` to be available. Having to install packages to scan them doesn't really make sense for me.

Failing that, an official `snyk/snyk-cli:pipenv` image would be nice

**Comment by verkaufer** [comment]
@adrukh Does Snyk plan on supporting Pipfiles for GitHub repositories? Right now the [documentation](https://snyk.io/docs/snyk-for-python/) only lists Pipfile support for the CLI, but it would be beneficial if Snyk could evaluate Pipfiles in PRs.

**Comment by lili2311** [comment]
@verkaufer It is indeed on our radar, but no definite date yet that I can share.

**Comment by DingGGu** [comment]
@lili2311 For pipenv purposes, it is better to scan the `Pipfile.lock` file than to scan the `Pipfile`. Please consider supporting `Pipfile.lock`.

**Comment by lili2311** [comment]
👋 @DingGGu just wanted to say this is not forgotten and we are planning a spike to support scanning the Pipfile projects directly from the lockfile :) Stay tuned!

**Comment by DingGGu** [comment]
👀

**Comment by lili2311** [comment]
@jsf9k we have released `setup.py` support a little while back, please try it out. It is supported via `--file=setuppy` only at the moment.

**Comment by mkj28** [comment]
@lili2311 can you clarify if the work in progress includes both Pipfile.lock support and github scanning?

**Comment by lili2311** [comment]
@mkj28 We are indeed doing some spikes to see what it takes to add this support, we have no dates to share for this as yet.

**Comment by jonapich** [comment]
@lili2311 I was able to make this work through the dockerfile with minimal changes; see PR above.

**Comment by mkj28** [comment]
> I was able to make this work through the dockerfile with minimal changes; see PR above.

@jonapich looks promising - did it work though? :)

**Comment by jonapich** [comment]
> @jonapich looks promising - did it work though? :) 

Yeah it did. Makes me wonder if they just forgot to update this ticket.

**Comment by lili2311** [comment]
Yep Pipfile is now supported! Closing the issue, re-open if needed.

**Comment by jeremywadsack** [comment]
Is `Pipfile.lock` (or even `Pipfile`) supported though GitHub? It doesn't show up when I imported the project and doesn't appear to be documented ([docs](https://docs.snyk.io/products/snyk-open-source/language-and-package-manager-support/snyk-for-python) still just say "CLI" and "Licensing" for `pipenv`.
