### ISSUE TITLE
Snyk does not follow PyPI alternate package naming rules

### ISSUE THREAD

**Issue by scriptsrc** [snyk/snyk-python-plugin#85]
- `node -v`: `v12.4.0`
- `npm -v`: `6.9.0`
- `snyk -v`: `1.241.0`
- Command run:
```
$ snyk monitor
Monitoring /redacted/...
Required packages missing: blah-api, blah-env
```
```
$ pip freeze | grep "env\|api"
blah.api==19.2.0
blah.env==8.2.1
```

### Expected behaviour
Snyk should know that python package names on PyPI can interchange case, hyphens, periods, and underscores.

Reference:
https://packaging.python.org/guides/distributing-packages-using-setuptools/#name

From the article:

> For example, if you register a project named cool-stuff, users will be able to download it or declare a dependency on it using any of the following spellings:

```
Cool-Stuff
cool.stuff
COOL_STUFF
CoOl__-.-__sTuFF
```

### Actual behaviour
Snyk balks at *any* string inequality between how a package is referenced in `Pipfile` vs what is shown in a `pip freeze`.

### Steps to reproduce
Use a `Pipfile` where a package is referenced slightly differently than what is outputted by `pip freeze`.

---

It looks like the problem is in `pip_resolve.py` on line 253:
https://github.com/snyk/snyk-python-plugin/blob/master/pysrc/pip_resolve.py#L253

`if r.name not in installed`

**Comment by scriptsrc** [comment]
(PR #86 filed to fix this.)

**Comment by orsagie** [comment]
Merged your PR, thank you for your contribution!
