### ISSUE TITLE
How to pass `--allow-missing` from `snyk` to `pip_resolve.py`?

### ISSUE THREAD

**Issue by scriptsrc** [snyk/snyk-python-plugin#87]
Question:

How do I get `snyk` to pass `--allow-missing` to `pip_resolve.py` ?

I don't see any cli arguments on `snyk` that would pass the value and I can't seem to find documentation on whether this is something that would go into the `.snyk` policy file.

We have internal projects that rely on other internal projects. I just want `snyk` to scan the OSS dependencies. It looks like `pip_resolve.py` has the plumbing. I just need to figure out how to get the `snyk` cli to pass the right values.

Unfortunately typescript/javascript are not my strengths. I poked around in the other code base and couldn't figure it out.

**Comment by thisislawatts** [comment]
Hey @scriptsrc.

You can pass arguments through to `pip_resolve.py` via the Snyk CLI using `--`. So to test your file locally you could do so with:

```
snyk test -- --allow-missing
```

Hope that helps :)

**Comment by scriptsrc** [comment]
Thank you so much.
